#!/bin/bash
echo "hello guys welcome to git class"
echo "hello guys welcome to git class"
echo "hello guys welcome to git class"
echo "hello guys welcome to git class"
echo "hello guys welcome to git class"
echo "hello guys welcome to git class"
echo "hello guys welcome to git class"
echo "hello guys welcome to git class"
echo "hello guys welcome to git class"
echo "hello guys welcome to git class"
echo "hello guys welcome to git class"
echo "hello guys welcome to git class"
echo "jdsjit ds s" 
